module.exports = Object.freeze({
  USE_STATE_CODE_USED: 1,
  USE_STATE_CODE_NOTUSED: 0,
  CHANNEL_TYPE_ONE: 1,
  CHANNEL_TYPE_GROUP: 2,
  CHANNEL_LIMIT_DEFAULT: 100,
  CHANNEL_STATE_DEACTIVE: 0,
  CHANNEL_STATE_ACTIVE: 1,
  MEMBER_TYPE_OWNER: 0,
  MEMBER_TYPE_MEMBER: 0,
  MEMBER_STATE_LOGIN_IN: 0,
  MEMBER_STATE_LOGIN_OUT: 1,
});